# Generated by Django 4.1.7 on 2023-03-06 17:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1024)),
                ('price', models.IntegerField()),
                ('available', models.IntegerField()),
            ],
        ),
    ]
