# Generated by Django 4.1.7 on 2023-03-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_image_seller_vote_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_certified',
            field=models.BooleanField(default=False),
        ),
    ]
